### ISSUE TITLE
User/Password authentification

### ISSUE THREAD

**Issue by jbr1989** [rsmacapinlac/docker-obsidian#2]
I have a docker server with this image installed and I use it for connect to obsidian everywhere. But, I worry about security. 

I see that is posible set PASSWORD in docker argument, but can't set USER.

Would be set both configuration in docker arguments?

Thanks

**Comment by rsmacapinlac** [comment]
@jbr1989 since I'm using the linuxserver.io base image, I believe that you can set the following.

- CUSTOM_USER
- PASSWORD

Have a look here: https://github.com/linuxserver/docker-baseimage-kasmvnc
